# Source: core/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-app
  labels:
    chart: core-2.8.6
    release: neuvector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neuvector-binding-app
subjects:
- kind: ServiceAccount
  name: default
  namespace: pham-test
---
# Source: core/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-rbac
  labels:
    chart: core-2.8.6
    release: neuvector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neuvector-binding-rbac
subjects:
- kind: ServiceAccount
  name: default
  namespace: pham-test
---
# Source: core/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-admission
  labels:
    chart: core-2.8.6
    release: neuvector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neuvector-binding-admission
subjects:
- kind: ServiceAccount
  name: default
  namespace: pham-test
---
# Source: core/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-view
  labels:
    chart: core-2.8.6
    release: neuvector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: default
  namespace: pham-test
