# Source: core/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-app
  labels:
    chart: core-2.8.6
    release: neuvector
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - services
  - namespaces
  verbs:
  - get
  - list
  - watch
  - update
---
# Source: core/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-rbac
  labels:
    chart: core-2.8.6
    release: neuvector
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  - clusterrolebindings
  - clusterroles
  verbs:
  - get
  - list
  - watch
---
# Source: core/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-admission
  labels:
    chart: core-2.8.6
    release: neuvector
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
# Source: core/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-nvgroupdefinitions
  labels:
    chart: core-2.8.6
    release: neuvector
rules:
- apiGroups:
  - neuvector.com
  resources:
  - nvgroupdefinitions
  verbs:
  - get
  - list
  - delete
