---
# Source: core/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neuvector-binding-secret
  namespace: pham-test
  labels:
    chart: core-2.8.6
    release: neuvector
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
# Source: core/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neuvector-binding-lease
  namespace: pham-test
  labels:
    chart: core-2.8.6
    release: neuvector
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
---
# Source: core/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neuvector-binding-job-creation
  namespace: pham-test
  labels:
    chart: core-2.8.6
    release: neuvector
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - delete
- apiGroups:
  - batch
  resources:
  - cronjobs
  - cronjobs/finalizers
  verbs:
  - update
  - patch
---
# Source: core/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neuvector-binding-cert-upgrader
  namespace: pham-test
  labels:
    chart: core-2.8.6
    release: neuvector
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - update
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - "apps"
  resources:
  - deployments
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - update
---
# Source: core/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neuvector-binding-secret-controller
  namespace: pham-test
  labels:
    chart: core-2.8.6
    release: neuvector
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - patch
