---
# Source: monitor/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: neuvector-prometheus-exporter-pod-secret
  namespace: pham-test
  labels:
    chart: monitor-2.8.6
    release: release-name
    heritage: Helm
type: Opaque
data:
  CTRL_USERNAME: "YWRtaW4="
  CTRL_PASSWORD: "YWRtaW4="
---
# Source: monitor/templates/exporter-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: neuvector-prometheus-exporter
  namespace: pham-test
  labels:
    chart: monitor-2.8.6
    release: release-name
    heritage: Helm
    app: neuvector-prometheus-exporter
spec:
  type: ClusterIP
  ports:
    - port: 8068
      name: metrics
      targetPort: 8068
      protocol: TCP
      appProtocol: http
  selector:
    app: neuvector-prometheus-exporter-pod
---
# Source: monitor/templates/exporter-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuvector-prometheus-exporter-pod
  namespace: pham-test
  labels:
    chart: monitor-2.8.6
    release: release-name
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuvector-prometheus-exporter-pod
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8068"
        prometheus.io/scrape: "true"
        checksum/secret: 9498b0e7290a4de7bb1afeb4b06936e25091fd86a349f093f02185b1c6980199
      labels:
        app: neuvector-prometheus-exporter-pod
        release: release-name
    spec:
      containers:
        - name: neuvector-prometheus-exporter-pod
          
          image: "docker.io/neuvector/prometheus-exporter:1.0.5"
          imagePullPolicy: IfNotPresent
          env:
            - name: CTRL_API_SERVICE
              value: neuvector-svc-controller-api:10443
            - name: EXPORTER_PORT
              value: "8068"
          envFrom:
            - secretRef:
                name: neuvector-prometheus-exporter-pod-secret
          ports:
           - name: metrics
             containerPort: 8068
             protocol: TCP
      restartPolicy: Always
